### PR TITLE
feat(litcoffee): add support for litcoffee files

### PR DESCRIPTION
**Pull request by carlrosell**
Added simple support for .litcoffee and coffee.md files.

### CODE REVIEW

**Comment by CaryLandholt** [comment]
Thanks, but why the need for the `litcoffeeToCoffee` function?

**Comment by carlrosell** [comment]
I use that function elsewhere but here it could be inlined instead.

**Comment by CaryLandholt** [comment]
What is the function accomplishing?  I'm not questioning if it should be inline or not. :)

**Comment by carlrosell** [comment]
Oh, I'm sorry. That function gets all `code blocks` and just removes the indentation.

It will take:

```
#This is my litcoffee file.

    class My extends Controller

Constructor for my controller

        constructor:($scope) ->
```

And return:

```
class My extends Controller   
    constructor:($scope) ->
```

**Comment by CaryLandholt** [comment]
Is this specifically to get ng-classify to work?

Can you take a look at the core [ng-classify](https://github.com/CaryLandholt/ng-classify) library?  The fix may need to go there.  Then developers would only need to include selectors they wish to support (e.g. `'**.*.{litcoffee,coffee,coffee.md}'`).

Since I support [grunt](https://github.com/CaryLandholt/grunt-ng-classify), [gulp](https://github.com/CaryLandholt/gulp-ng-classify), and [broccoli](https://github.com/CaryLandholt/broccoli-ng-classify), I'd like to take care of this in one shot.  Will also need unit tests.  There also exists a [RubyGem](https://rubygems.org/gems/ng_classify).

Thanks,
Cary

**Pull request closed without merging**
